// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_Del(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// del non-existent
	if got := sess.Del("k1"); got != 0 {
		t.Errorf("Del(k1) = %d, want 0", got)
	}

	// del existing
	sess.Exec("SET k1 v1")
	sess.Exec("SET k2 v2")
	if got := sess.Del("k1", "k2"); got != 2 {
		t.Errorf("Del(k1, k2) = %d, want 2", got)
	}

	// verify deleted
	_, ok := sess.Get("k1")
	if ok {
		t.Error("k1 should be deleted")
	}
}

func TestSession_DelField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// del field on non-existent key
	err = sess.DelField("k1", []string{"a"})
	if err == nil {
		t.Error("DelField(k1.a) should return error")
	}

	// del field on existing
	sess.Exec(`SET obj {"a":1,"b":2}`)
	err = sess.DelField("obj", []string{"a"})
	if err != nil {
		t.Errorf("DelField(obj.a): %v", err)
	}

	// verify field deleted
	val, ok := sess.GetField("obj", []string{"a"})
	if ok {
		t.Errorf("obj.a should be deleted, got %q", val)
	}
}
