// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/agenvoy/toriidb/core/store"
)

func TestExec_Get(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// GET non-existent
	if got := sess.Exec("GET k1"); got != "(nil)" {
		t.Errorf("Exec(GET k1) = %q, want (nil)", got)
	}

	// SET then GET
	sess.Exec("SET k1 hello")
	if got := sess.Exec("GET k1"); got != "hello" {
		t.Errorf("Exec(GET k1) = %q, want hello", got)
	}

	// GET with dot notation
	sess.Exec(`SET obj {"a":{"b":"world"}}`)
	if got := sess.Exec("GET obj.a.b"); got != "world" {
		t.Errorf("Exec(GET obj.a.b) = %q, want world", got)
	}
}

func TestExec_Set(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// SET
	if got := sess.Exec("SET k1 v1"); got != "OK" {
		t.Errorf("Exec(SET) = %q, want OK", got)
	}

	// SET NX
	if got := sess.Exec("SET k1 v2 NX"); got != "(nil)" {
		t.Errorf("Exec(SET NX) = %q, want (nil)", got)
	}

	// SET XX
	if got := sess.Exec("SET k1 v2 XX"); got != "OK" {
		t.Errorf("Exec(SET XX) = %q, want OK", got)
	}

	// SET with expiry
	if got := sess.Exec("SET k2 v2 3600"); got != "OK" {
		t.Errorf("Exec(SET with expiry) = %q, want OK", got)
	}
}

func TestExec_Del(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec("SET k1 v1")
	sess.Exec("SET k2 v2")

	if got := sess.Exec("DEL k1 k2"); got != "(integer) 2" {
		t.Errorf("Exec(DEL) = %q, want (integer) 2", got)
	}

	// DEL field
	sess.Exec(`SET obj {"a":1,"b":2}`)
	if got := sess.Exec("DEL obj.a"); got != "OK" {
		t.Errorf("Exec(DEL obj.a) = %q, want OK", got)
	}
}

func TestExec_Keys(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// empty
	if got := sess.Exec("KEYS *"); got != "(empty list)" {
		t.Errorf("Exec(KEYS *) on empty = %q, want (empty list)", got)
	}

	sess.Exec("SET a 1")
	sess.Exec("SET b 2")
	if got := sess.Exec("KEYS *"); got == "(empty list)" {
		t.Error("Exec(KEYS *) should not be empty")
	}
}

func TestExec_Exist(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.Exec("EXIST k1"); got != "(integer) 0" {
		t.Errorf("Exec(EXIST k1) = %q, want (integer) 0", got)
	}

	sess.Exec("SET k1 v1")
	if got := sess.Exec("EXIST k1"); got != "(integer) 1" {
		t.Errorf("Exec(EXIST k1) = %q, want (integer) 1", got)
	}
}

func TestExec_Type(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.Exec("TYPE k1"); got != "(nil)" {
		t.Errorf("Exec(TYPE k1) = %q, want (nil)", got)
	}

	sess.Exec("SET k1 hello")
	if got := sess.Exec("TYPE k1"); got != "string" {
		t.Errorf("Exec(TYPE k1) = %q, want string", got)
	}
}

func TestExec_TTL_Expire_Persist(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// TTL non-existent
	if got := sess.Exec("TTL k1"); got != "(nil)" {
		t.Errorf("Exec(TTL k1) = %q, want (nil)", got)
	}

	// EXPIRE
	sess.Exec("SET k1 v1")
	if got := sess.Exec("EXPIRE k1 3600"); got != "OK" {
		t.Errorf("Exec(EXPIRE) = %q, want OK", got)
	}

	// PERSIST
	if got := sess.Exec("PERSIST k1"); got != "OK" {
		t.Errorf("Exec(PERSIST) = %q, want OK", got)
	}
}

func TestExec_Incr(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec("SET n 10")
	if got := sess.Exec("INCR n"); got != "11" {
		t.Errorf("Exec(INCR n) = %q, want 11", got)
	}

	if got := sess.Exec("INCR n 5"); got != "16" {
		t.Errorf("Exec(INCR n 5) = %q, want 16", got)
	}

	// INCR field
	sess.Exec(`SET obj {"count":10}`)
	if got := sess.Exec("INCR obj.count 5"); got != "15" {
		t.Errorf("Exec(INCR obj.count 5) = %q, want 15", got)
	}
}

func TestExec_Find(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec("SET k1 hello")
	sess.Exec("SET k2 world")

	if got := sess.Exec("FIND EQ hello"); got == "(empty list)" {
		t.Error("Exec(FIND EQ hello) should not be empty")
	}
}

func TestExec_Query(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec(`SET u1 {"name":"alice","age":30}`)
	sess.Exec(`SET u2 {"name":"bob","age":25}`)

	if got := sess.Exec("QUERY name EQ alice"); got == "(empty list)" {
		t.Error("Exec(QUERY) should not be empty")
	}
}

func TestExec_Select(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.Exec("SELECT 5"); got != "OK" {
		t.Errorf("Exec(SELECT 5) = %q, want OK", got)
	}
	if got := sess.Exec("SELECT 16"); got == "OK" {
		t.Error("Exec(SELECT 16) should return error")
	}
}

func TestExec_Unknown(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	if got := sess.Exec("UNKNOWN cmd"); got == "" {
		t.Error("Exec(UNKNOWN) should not be empty")
	}
}

func TestExec_Empty(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()
	if got := sess.Exec(""); got != "" {
		t.Errorf("Exec('') = %q, want ''", got)
	}
}