// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
	"github.com/pardnchiu/toriidb/core/store/filter"
)

func TestSession_Find(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// empty
	results := sess.Find(filter.EqualTo, "hello", 10)
	if len(results) != 0 {
		t.Errorf("Find on empty = %v, want []", results)
	}

	// with data
	sess.Exec("SET k1 hello")
	sess.Exec("SET k2 world")

	results = sess.Find(filter.EqualTo, "hello", 10)
	if len(results) != 1 {
		t.Errorf("Find EQ hello = %d results, want 1", len(results))
	}

	// NE
	results = sess.Find(filter.NotEqualTo, "hello", 10)
	if len(results) != 1 {
		t.Errorf("Find NE hello = %d results, want 1", len(results))
	}
}

func TestSession_Find_Limit(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec("SET k1 v")
	sess.Exec("SET k2 v")
	sess.Exec("SET k3 v")

	results := sess.Find(filter.EqualTo, "v", 2)
	if len(results) > 2 {
		t.Errorf("Find limit 2 = %d results, want <= 2", len(results))
	}
}
