// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/agenvoy/toriidb/core/store"
)

func TestSession_Get(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// non-existent
	entry, ok := sess.Get("k1")
	if ok {
		t.Error("Get(k1) should return false")
	}
	if entry != nil {
		t.Error("Get(k1) should return nil entry")
	}

	// existing
	sess.Exec("SET k1 hello")
	entry, ok = sess.Get("k1")
	if !ok {
		t.Fatal("Get(k1) should return true")
	}
	if entry.Value() != "hello" {
		t.Errorf("Get(k1).Value() = %q, want hello", entry.Value())
	}
}

func TestSession_GetField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// non-existent key
	val, ok := sess.GetField("k1", []string{"a"})
	if ok {
		t.Error("GetField(k1.a) should return false")
	}
	if val != "" {
		t.Errorf("GetField(k1.a) = %q, want ''", val)
	}

	// existing
	sess.Exec(`SET obj {"a":{"b":"world"}}`)
	val, ok = sess.GetField("obj", []string{"a", "b"})
	if !ok {
		t.Fatal("GetField(obj.a.b) should return true")
	}
	if val != "world" {
		t.Errorf("GetField(obj.a.b) = %q, want world", val)
	}
}

func TestSession_Exist(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.Exist("k1"); got != "(integer) 0" {
		t.Errorf("Exist(k1) = %q, want (integer) 0", got)
	}

	sess.Exec("SET k1 v1")
	if got := sess.Exist("k1"); got != "(integer) 1" {
		t.Errorf("Exist(k1) = %q, want (integer) 1", got)
	}
}

func TestSession_ExistField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.ExistField("k1", []string{"a"}); got != "(integer) 0" {
		t.Errorf("ExistField(k1.a) = %q, want (integer) 0", got)
	}

	sess.Exec(`SET obj {"a":1}`)
	if got := sess.ExistField("obj", []string{"a"}); got != "(integer) 1" {
		t.Errorf("ExistField(obj.a) = %q, want (integer) 1", got)
	}
}

func TestSession_Type(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.Type("k1"); got != "(nil)" {
		t.Errorf("Type(k1) = %q, want (nil)", got)
	}

	sess.Exec("SET k1 hello")
	if got := sess.Type("k1"); got != "string" {
		t.Errorf("Type(k1) = %q, want string", got)
	}
}

func TestSession_TypeField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	if got := sess.TypeField("k1", []string{"a"}); got != "(nil)" {
		t.Errorf("TypeField(k1.a) = %q, want (nil)", got)
	}

	sess.Exec(`SET obj {"a":1}`)
	if got := sess.TypeField("obj", []string{"a"}); got != "int" {
		t.Errorf("TypeField(obj.a) = %q, want int", got)
	}
}