// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"os"
	"path/filepath"
	"testing"
)

func tempDir(t *testing.T) string {
	t.Helper()
	// Use project-local temp to avoid macOS sandbox /var/folders permission issues.
	// Resolve relative to the test file's directory (core/store/), then up to project root.
	base := filepath.Join("..", "..", ".gotmp", "toriidb-test")
	abs, err := filepath.Abs(base)
	if err != nil {
		t.Fatalf("filepath.Abs: %v", err)
	}
	if err := os.MkdirAll(abs, 0755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	dir, err := os.MkdirTemp(abs, "*")
	if err != nil {
		t.Fatalf("MkdirTemp: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(dir) })
	return dir
}