// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_Incr(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// incr non-existent — implementation does not auto-create
	_, err = sess.Incr("n", 1)
	if err == nil {
		t.Error("Incr(n, 1) on non-existent key should return error")
	}

	// incr existing
	sess.Exec("SET n 0")
	val, err := sess.Incr("n", 1)
	if err != nil {
		t.Fatalf("Incr(n, 1): %v", err)
	}
	if val != 1 {
		t.Errorf("Incr(n, 1) = %v, want 1", val)
	}

	// incr existing
	val, err = sess.Incr("n", 5)
	if err != nil {
		t.Fatalf("Incr(n, 5): %v", err)
	}
	if val != 6 {
		t.Errorf("Incr(n, 5) = %v, want 6", val)
	}

	// incr negative
	val, err = sess.Incr("n", -2)
	if err != nil {
		t.Fatalf("Incr(n, -2): %v", err)
	}
	if val != 4 {
		t.Errorf("Incr(n, -2) = %v, want 4", val)
	}
}
