// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_IncrField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// incr field on non-existent key
	_, err = sess.IncrField("k1", []string{"a"}, 1)
	if err == nil {
		t.Error("IncrField(k1.a) should return error")
	}

	// incr field on existing
	sess.Exec(`SET obj {"count":10}`)
	val, err := sess.IncrField("obj", []string{"count"}, 5)
	if err != nil {
		t.Fatalf("IncrField(obj.count, 5): %v", err)
	}
	if val != 15 {
		t.Errorf("IncrField(obj.count, 5) = %v, want 15", val)
	}

	// incr field negative
	val, err = sess.IncrField("obj", []string{"count"}, -3)
	if err != nil {
		t.Fatalf("IncrField(obj.count, -3): %v", err)
	}
	if val != 12 {
		t.Errorf("IncrField(obj.count, -3) = %v, want 12", val)
	}
}
