// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_Keys(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// empty
	if got := sess.Keys("*"); len(got) != 0 {
		t.Errorf("Keys(*) on empty = %v, want []", got)
	}

	// with data
	sess.Exec("SET a 1")
	sess.Exec("SET b 2")
	sess.Exec("SET ab 3")

	keys := sess.Keys("*")
	if len(keys) != 3 {
		t.Errorf("Keys(*) = %d items, want 3", len(keys))
	}

	// pattern
	keys = sess.Keys("a*")
	if len(keys) != 2 {
		t.Errorf("Keys(a*) = %d items, want 2", len(keys))
	}
}
