// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/agenvoy/toriidb/core/store"
	"github.com/agenvoy/toriidb/core/store/filter"
)

func TestSession_Query(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// empty
	results := sess.Query(filter.Cond{Field: "name", Op: filter.EqualTo, Value: "alice"}, 10)
	if len(results) != 0 {
		t.Errorf("Query on empty = %v, want []", results)
	}

	// with data
	sess.Exec(`SET u1 {"name":"alice","age":30}`)
	sess.Exec(`SET u2 {"name":"bob","age":25}`)

	results = sess.Query(filter.Cond{Field: "name", Op: filter.EqualTo, Value: "alice"}, 10)
	if len(results) != 1 {
		t.Errorf("Query = %d results, want 1", len(results))
	}
}

func TestSession_Query_Limit(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	sess.Exec(`SET u1 {"name":"alice"}`)
	sess.Exec(`SET u2 {"name":"bob"}`)
	sess.Exec(`SET u3 {"name":"charlie"}`)

	results := sess.Query(filter.Cond{Field: "name", Op: filter.NotEqualTo, Value: ""}, 2)
	if len(results) > 2 {
		t.Errorf("Query limit 2 = %d results, want <= 2", len(results))
	}
}