// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_SetField(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// set field on non-existent key — implementation creates a new JSON object
	err = sess.SetField("k1", []string{"a"}, "1", store.SetDefault, nil)
	if err != nil {
		t.Errorf("SetField(k1.a) on non-existent key: %v", err)
	}

	// verify it was created
	val, ok := sess.GetField("k1", []string{"a"})
	if !ok {
		t.Fatal("GetField(k1.a) should return true after SetField")
	}
	if val != "1" {
		t.Errorf("GetField(k1.a) = %q, want 1", val)
	}

	// set field on existing
	sess.Exec(`SET obj {"a":1}`)
	err = sess.SetField("obj", []string{"a"}, "2", store.SetDefault, nil)
	if err != nil {
		t.Errorf("SetField(obj.a, 2): %v", err)
	}

	// verify
	val, ok = sess.GetField("obj", []string{"a"})
	if !ok {
		t.Fatal("GetField(obj.a) should return true")
	}
	if val != "2" {
		t.Errorf("GetField(obj.a) = %q, want 2", val)
	}
}
