// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_TTL(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// TTL non-existent
	if got := sess.TTL("k1"); got != -2 {
		t.Errorf("TTL(k1) = %d, want -2", got)
	}

	// TTL persistent
	sess.Exec("SET k1 v1")
	if got := sess.TTL("k1"); got != -1 {
		t.Errorf("TTL(k1) = %d, want -1", got)
	}
}

func TestSession_Expire(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// expire non-existent
	err = sess.Expire("k1", 3600)
	if err == nil {
		t.Error("Expire(k1) should return error")
	}

	// expire existing
	sess.Exec("SET k1 v1")
	err = sess.Expire("k1", 3600)
	if err != nil {
		t.Errorf("Expire(k1, 3600): %v", err)
	}
}

func TestSession_ExpireAt(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// expireAt non-existent
	err = sess.ExpireAt("k1", 2000000000)
	if err == nil {
		t.Error("ExpireAt(k1) should return error")
	}

	// expireAt existing
	sess.Exec("SET k1 v1")
	err = sess.ExpireAt("k1", 2000000000)
	if err != nil {
		t.Errorf("ExpireAt(k1, 2000000000): %v", err)
	}
}

func TestSession_Persist(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// persist non-existent
	err = sess.Persist("k1")
	if err == nil {
		t.Error("Persist(k1) should return error")
	}

	// persist existing
	sess.Exec("SET k1 v1")
	err = sess.Persist("k1")
	if err != nil {
		t.Errorf("Persist(k1): %v", err)
	}
}
