// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"context"
	"testing"

	"github.com/pardnchiu/toriidb/core/store"
)

func TestSession_VSearch(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// VSearch may fail if no OPENAI_API_KEY
	results, err := sess.VSearch(context.Background(), "hello", "*", 10)
	if err != nil {
		t.Logf("VSearch failed (expected without API key): %v", err)
		return
	}
	// If it succeeds, results should be a slice (possibly empty)
	if results == nil {
		t.Error("VSearch returned nil slice")
	}
}

func TestSession_VSearch_CanceledContext(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err = sess.VSearch(ctx, "hello", "*", 10)
	if err == nil {
		t.Log("VSearch with canceled context did not error (may not have embedder)")
	}
}

func TestSession_VSearch_EmptyText(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	_, err = sess.VSearch(context.Background(), "", "*", 10)
	if err == nil {
		t.Log("VSearch with empty text did not error")
	}
}

func TestSession_VSearch_ZeroK(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	results, err := sess.VSearch(context.Background(), "hello", "*", 0)
	if err != nil {
		t.Logf("VSearch with k=0 failed: %v", err)
		return
	}
	if results == nil {
		t.Error("VSearch returned nil slice")
	}
}

func TestSession_VSearch_NilContext(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	_, err = sess.VSearch(nil, "hello", "*", 10)
	if err == nil {
		t.Log("VSearch with nil context did not error")
	}
}

func TestSession_VSearch_Pattern(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	results, err := sess.VSearch(context.Background(), "hello", "nonexistent*", 10)
	if err != nil {
		t.Logf("VSearch with pattern failed: %v", err)
		return
	}
	if results == nil {
		t.Error("VSearch returned nil slice")
	}
}
