// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package store_test

import (
	"testing"

	"github.com/agenvoy/toriidb/core/store"
)

func TestSession_VSim(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// VSim on non-existent keys
	_, err = sess.VSim("k1", "k2")
	if err == nil {
		t.Error("VSim(k1, k2) should return error")
	}
}

func TestSession_VGet(t *testing.T) {
	s, err := store.New(tempDir(t))
	if err != nil {
		t.Fatalf("store.New: %v", err)
	}
	defer s.Close()

	sess := s.Session()

	// VGet non-existent
	vec, ok := sess.VGet("k1")
	if ok {
		t.Error("VGet(k1) should return false")
	}
	if vec != nil {
		t.Error("VGet(k1) should return nil vector")
	}
}