// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package filter_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store/filter"
)

func TestAnd_Match(t *testing.T) {
	tests := []struct {
		name  string
		and   filter.And
		input any
		want  bool
	}{
		{
			name: "all match",
			and: filter.And{
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"},
				filter.Cond{Field: "b", Op: filter.EqualTo, Value: "2"},
			},
			input: map[string]any{"a": "1", "b": "2"},
			want:  true,
		},
		{
			name: "one mismatch",
			and: filter.And{
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"},
				filter.Cond{Field: "b", Op: filter.EqualTo, Value: "2"},
			},
			input: map[string]any{"a": "1", "b": "3"},
			want:  false,
		},
		{
			name:  "empty and",
			and:   filter.And{},
			input: map[string]any{},
			want:  true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.and.Match(tt.input); got != tt.want {
				t.Errorf("And.Match() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestOr_Match(t *testing.T) {
	tests := []struct {
		name  string
		or    filter.Or
		input any
		want  bool
	}{
		{
			name: "first matches",
			or: filter.Or{
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"},
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "2"},
			},
			input: map[string]any{"a": "1"},
			want:  true,
		},
		{
			name: "second matches",
			or: filter.Or{
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"},
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "2"},
			},
			input: map[string]any{"a": "2"},
			want:  true,
		},
		{
			name: "none match",
			or: filter.Or{
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"},
				filter.Cond{Field: "a", Op: filter.EqualTo, Value: "2"},
			},
			input: map[string]any{"a": "3"},
			want:  false,
		},
		{
			name:  "empty or",
			or:    filter.Or{},
			input: map[string]any{},
			want:  false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.or.Match(tt.input); got != tt.want {
				t.Errorf("Or.Match() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestNot_Match(t *testing.T) {
	tests := []struct {
		name  string
		not   filter.Not
		input any
		want  bool
	}{
		{
			name:  "negates true",
			not:   filter.Not{filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"}},
			input: map[string]any{"a": "1"},
			want:  false,
		},
		{
			name:  "negates false",
			not:   filter.Not{filter.Cond{Field: "a", Op: filter.EqualTo, Value: "1"}},
			input: map[string]any{"a": "2"},
			want:  true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.not.Match(tt.input); got != tt.want {
				t.Errorf("Not.Match() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestEQ_Match(t *testing.T) {
	c := filter.EQ{Field: "x", Value: "1"}
	if !c.Match(map[string]any{"x": "1"}) {
		t.Error("EQ.Match should be true")
	}
	if c.Match(map[string]any{"x": "2"}) {
		t.Error("EQ.Match should be false")
	}
	if c.Match(map[string]any{"y": "1"}) {
		t.Error("EQ.Match should be false for missing field")
	}
	if c.Match(nil) {
		t.Error("EQ.Match should be false for nil")
	}
}

func TestNE_Match(t *testing.T) {
	c := filter.NE{Field: "x", Value: "1"}
	if !c.Match(map[string]any{"x": "2"}) {
		t.Error("NE.Match should be true")
	}
	if c.Match(map[string]any{"x": "1"}) {
		t.Error("NE.Match should be false")
	}
}

func TestGT_Match(t *testing.T) {
	c := filter.GT{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 20.0}) {
		t.Error("GT.Match should be true")
	}
	if c.Match(map[string]any{"x": 5.0}) {
		t.Error("GT.Match should be false")
	}
}

func TestGTE_Match(t *testing.T) {
	c := filter.GTE{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 10.0}) {
		t.Error("GTE.Match should be true for equal")
	}
	if !c.Match(map[string]any{"x": 20.0}) {
		t.Error("GTE.Match should be true for greater")
	}
}

func TestGE_Match(t *testing.T) {
	c := filter.GE{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 10.0}) {
		t.Error("GE.Match should be true for equal")
	}
}

func TestLT_Match(t *testing.T) {
	c := filter.LT{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 5.0}) {
		t.Error("LT.Match should be true")
	}
	if c.Match(map[string]any{"x": 20.0}) {
		t.Error("LT.Match should be false")
	}
}

func TestLTE_Match(t *testing.T) {
	c := filter.LTE{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 10.0}) {
		t.Error("LTE.Match should be true for equal")
	}
	if !c.Match(map[string]any{"x": 5.0}) {
		t.Error("LTE.Match should be true for less")
	}
}

func TestLE_Match(t *testing.T) {
	c := filter.LE{Field: "x", Value: "10"}
	if !c.Match(map[string]any{"x": 5.0}) {
		t.Error("LE.Match should be true for less")
	}
}

func TestLIKE_Match(t *testing.T) {
	c := filter.LIKE{Field: "x", Value: "hel*"}
	if !c.Match(map[string]any{"x": "hello"}) {
		t.Error("LIKE.Match should be true")
	}
	if c.Match(map[string]any{"x": "world"}) {
		t.Error("LIKE.Match should be false")
	}
}
