// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package filter_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store/filter"
)

func TestCond_Match(t *testing.T) {
	tests := []struct {
		name  string
		cond  filter.Cond
		input any
		want  bool
	}{
		{
			name:  "simple equal match",
			cond:  filter.Cond{Field: "name", Op: filter.EqualTo, Value: "alice"},
			input: map[string]any{"name": "alice"},
			want:  true,
		},
		{
			name:  "simple equal mismatch",
			cond:  filter.Cond{Field: "name", Op: filter.EqualTo, Value: "bob"},
			input: map[string]any{"name": "alice"},
			want:  false,
		},
		{
			name:  "nested field match",
			cond:  filter.Cond{Field: "user.age", Op: filter.GreaterThan, Value: "18"},
			input: map[string]any{"user": map[string]any{"age": 25.0}},
			want:  true,
		},
		{
			name:  "nested field mismatch",
			cond:  filter.Cond{Field: "user.age", Op: filter.LessThan, Value: "18"},
			input: map[string]any{"user": map[string]any{"age": 25.0}},
			want:  false,
		},
		{
			name:  "field not found",
			cond:  filter.Cond{Field: "missing", Op: filter.EqualTo, Value: "x"},
			input: map[string]any{"name": "alice"},
			want:  false,
		},
		{
			name:  "nil input",
			cond:  filter.Cond{Field: "x", Op: filter.EqualTo, Value: "y"},
			input: nil,
			want:  false,
		},
		{
			name:  "zero-value cond",
			cond:  filter.Cond{},
			input: map[string]any{"": ""},
			want:  false, // TODO: behavior assumption — empty field name resolves to full object, not empty-string key
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.cond.Match(tt.input); got != tt.want {
				t.Errorf("Cond.Match() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestAtoFilter(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"simple eq", "name EQ alice", false},
		{"gt numeric", "age GT 18", false},
		{"and expression", "name EQ alice AND age GT 18", false},
		{"or expression", "name EQ alice OR name EQ bob", false},
		{"not expression", "NOT name EQ alice", false},
		{"grouped expression", "(name EQ alice OR name EQ bob) AND age GT 18", false},
		{"empty string", "", true},
		{"invalid operator", "name INVALID alice", true},
		{"missing value", "name EQ", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f, err := filter.AtoFilter(tt.input)
			if (err != nil) != tt.wantErr {
				t.Errorf("AtoFilter() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if err == nil && f == nil {
				t.Error("AtoFilter() returned nil filter with no error")
			}
		})
	}
}

func TestAtoFilter_MatchIntegration(t *testing.T) {
	f, err := filter.AtoFilter("name EQ alice")
	if err != nil {
		t.Fatalf("AtoFilter: %v", err)
	}
	if !f.Match(map[string]any{"name": "alice"}) {
		t.Error("expected match for 'name EQ alice' on {name: alice}")
	}
	if f.Match(map[string]any{"name": "bob"}) {
		t.Error("expected no match for 'name EQ alice' on {name: bob}")
	}
}
