// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package filter_test

import (
	"testing"

	"github.com/pardnchiu/toriidb/core/store/filter"
)

func TestAtoOperation(t *testing.T) {
	tests := []struct {
		name   string
		input  string
		wantOp filter.Operator
		wantOk bool
	}{
		{"eq lowercase", "eq", filter.EqualTo, true},
		{"EQ uppercase", "EQ", filter.EqualTo, true},
		{"=", "=", filter.EqualTo, true},
		{"gt", "gt", filter.GreaterThan, true},
		{">", ">", filter.GreaterThan, true},
		{"gte", "gte", filter.GreaterThanOrEqualTo, true},
		{"ge", "ge", filter.GreaterThanOrEqualTo, true},
		{">=", ">=", filter.GreaterThanOrEqualTo, true},
		{"lt", "lt", filter.LessThan, true},
		{"<", "<", filter.LessThan, true},
		{"lte", "lte", filter.LessThanOrEqualTo, true},
		{"le", "le", filter.LessThanOrEqualTo, true},
		{"<=", "<=", filter.LessThanOrEqualTo, true},
		{"ne", "ne", filter.NotEqualTo, true},
		{"!=", "!=", filter.NotEqualTo, true},
		{"like", "like", filter.Like, true},
		{"LIKE uppercase", "LIKE", filter.Like, true},
		{"unknown", "UNKNOWN", 0, false},
		{"empty", "", 0, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotOp, gotOk := filter.AtoOperation(tt.input)
			if gotOk != tt.wantOk {
				t.Errorf("AtoOperation(%q) ok = %v, want %v", tt.input, gotOk, tt.wantOk)
			}
			if gotOk && gotOp != tt.wantOp {
				t.Errorf("AtoOperation(%q) op = %v, want %v", tt.input, gotOp, tt.wantOp)
			}
		})
	}
}

func TestMatch(t *testing.T) {
	tests := []struct {
		name   string
		stored string
		op     filter.Operator
		target string
		want   bool
	}{
		{"eq match", "hello", filter.EqualTo, "hello", true},
		{"eq mismatch", "hello", filter.EqualTo, "world", false},
		{"gt match", "10", filter.GreaterThan, "5", true},
		{"gt mismatch", "5", filter.GreaterThan, "10", false},
		{"gt non-numeric", "abc", filter.GreaterThan, "5", false},
		{"gte match equal", "10", filter.GreaterThanOrEqualTo, "10", true},
		{"gte match greater", "10", filter.GreaterThanOrEqualTo, "5", true},
		{"gte mismatch", "5", filter.GreaterThanOrEqualTo, "10", false},
		{"lt match", "5", filter.LessThan, "10", true},
		{"lt mismatch", "10", filter.LessThan, "5", false},
		{"lte match equal", "10", filter.LessThanOrEqualTo, "10", true},
		{"lte match less", "5", filter.LessThanOrEqualTo, "10", true},
		{"ne match", "hello", filter.NotEqualTo, "world", true},
		{"ne mismatch", "hello", filter.NotEqualTo, "hello", false},
		{"like prefix", "hello", filter.Like, "hel*", true},
		{"like suffix", "hello", filter.Like, "*llo", true},
		{"like contains", "hello", filter.Like, "*ell*", true},
		{"like exact", "hello", filter.Like, "hello", true},
		{"like no match", "hello", filter.Like, "world*", false},
		{"like star-only", "hello", filter.Like, "*", true},
		{"empty both", "", filter.EqualTo, "", true},
		{"empty stored eq", "", filter.EqualTo, "x", false},
		{"float compare", "3.14", filter.GreaterThan, "3.13", true},
		{"negative compare", "-5", filter.GreaterThan, "-10", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := filter.Match(tt.stored, tt.op, tt.target); got != tt.want {
				t.Errorf("Match(%q, %v, %q) = %v, want %v", tt.stored, tt.op, tt.target, got, tt.want)
			}
		})
	}
}
