// Generated by [go-test-generate](https://github.com/pardnio/skill-go-test-generate).
package filter_test

import (
	"strings"
	"testing"

	"github.com/agenvoy/toriidb/core/store/filter"
)

func newParser(input string) *filter.Parser {
	return &filter.Parser{Words: strings.Fields(input)}
}

func TestParser_Current(t *testing.T) {
	p := newParser("")
	if got := p.Current(); got != "" {
		t.Errorf("Current() = %q, want ''", got)
	}

	p = newParser("name EQ alice")
	if got := p.Current(); got != "name" {
		t.Errorf("Current() = %q, want name", got)
	}
}

func TestParser_Primary(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"empty", "", true},
		{"simple EQ", "name EQ alice", false},
		{"simple NE", "name NE bob", false},
		{"simple GT", "age GT 30", false},
		{"simple GTE", "age GTE 18", false},
		{"simple LT", "age LT 65", false},
		{"simple LTE", "age LTE 65", false},
		{"simple LIKE", "name LIKE ali*", false},
		{"unknown op", "name XX value", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := newParser(tt.input)
			_, err := p.Primary()
			if (err != nil) != tt.wantErr {
				t.Errorf("Primary() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestParser_Or(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"empty", "", true},
		{"single", "name EQ alice", false},
		{"or", "name EQ alice OR name EQ bob", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := newParser(tt.input)
			_, err := p.Or()
			if (err != nil) != tt.wantErr {
				t.Errorf("Or() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestParser_And(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"empty", "", true},
		{"single", "name EQ alice", false},
		{"and", "name EQ alice AND age GT 18", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := newParser(tt.input)
			_, err := p.And()
			if (err != nil) != tt.wantErr {
				t.Errorf("And() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestParser_Not(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"empty", "", true},
		{"not", "NOT name EQ alice", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := newParser(tt.input)
			_, err := p.Not()
			if (err != nil) != tt.wantErr {
				t.Errorf("Not() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}